Repository slnz/go, pull requests merged in 2022-07, with the labels that each got.

#1 chore: add storybook, basic story and documentation example
  .eslintrc.js
  .storybook/main.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/components/App/Introduction.stories.mdx
  src/pages/Login/Login.stories.tsx
  tsconfig.json
Labels: effort: 2, priority:2day, type: chore

#2 chore: add chromatic
  .github/workflows/chromatic.yml
  .gitignore
  package-lock.json
  package.json
Labels: effort: 2, priority:2day, type: chore

#3 chore: add unit test check
  .github/workflows/main.yml
Labels: effort: 2, priority: soon, type: chore

#4 feat: login with fluro
  .eslintrc.js
  .storybook/preview.tsx
  go.png
  package-lock.json
  package.json
  public/assets/go.png
  src/@types/fluro.d.ts
  src/components/App/App.spec.tsx
  src/components/App/App.tsx
  src/components/ForgotPassword/ForgotPassword.spec.tsx
  src/components/ForgotPassword/ForgotPassword.stories.tsx
  src/components/ForgotPassword/ForgotPassword.tsx
  src/components/ForgotPassword/index.ts
  src/components/Login/Login.spec.tsx
  src/components/Login/Login.stories.tsx
  src/components/Login/Login.tsx
  src/components/Login/index.ts
  src/components/Router/Router.tsx
  src/components/Router/index.ts
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/index.ts
  src/index.tsx
  src/lib/auth.ts
  src/lib/fluro/authentication.ts
  src/lib/fluro/client.ts
  src/lib/fluro/index.ts
  src/lib/fluro/util.ts
  src/lib/storage.ts
  src/lib/useAuth/index.ts
  src/lib/useAuth/useAuth.spec.tsx
  src/lib/useAuth/useAuth.tsx
  src/pages/ForgotPasswordPage/ForgotPasswordPage.stories.tsx
  src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
  src/pages/ForgotPasswordPage/index.ts
  src/pages/Login/Login.stories.tsx
  src/pages/Login/Login.tsx
  src/pages/LoginPage/LoginPage.stories.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/index.ts
  src/setupTests.ts
  src/theme/theme.ts
  tsconfig.json
Labels: effort: 3, priority: now, type: feat

#5 chore: add import ordering
  .eslintrc.js
  dangerfile.ts
  package-lock.json
  package.json
  src/components/App/App.spec.tsx
  src/components/App/App.tsx
  src/components/ForgotPassword/ForgotPassword.spec.tsx
  src/components/ForgotPassword/ForgotPassword.stories.tsx
  src/components/ForgotPassword/ForgotPassword.tsx
  src/components/Login/Login.spec.tsx
  src/components/Login/Login.stories.tsx
  src/components/Login/Login.tsx
  src/components/Router/Router.tsx
  src/components/Tabs/Tabs.tsx
  src/index.tsx
  src/lib/useAuth/useAuth.spec.tsx
  src/lib/useAuth/useAuth.tsx
  src/pages/ForgotPasswordPage/ForgotPasswordPage.stories.tsx
  src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
  src/pages/LoginPage/LoginPage.stories.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/reportWebVitals.ts
  src/serviceWorkerRegistration.ts
  src/setupTests.ts
Labels: effort: 1, priority: now, type: chore

#6 feat: add people menu bar
  .env
  .storybook/main.ts
  .storybook/preview.tsx
  src/components/App/App.tsx
  src/components/PeopleMenuBar/PeopleMenuBar.spec.tsx
  src/components/PeopleMenuBar/PeopleMenuBar.stories.tsx
  src/components/PeopleMenuBar/PeopleMenuBar.tsx
  src/components/PeopleMenuBar/index.ts
  src/components/Tabs/Tabs.tsx
  src/pages/Dashboard/Dashboard.tsx
  src/pages/Dashboard/index.ts
  src/pages/PeoplePage/PeoplePage.stories.tsx
  src/pages/PeoplePage/PeoplePage.tsx
  src/pages/PeoplePage/PersonDetailPage/PersonDetailPage.stories.tsx
  src/pages/PeoplePage/PersonDetailPage/PersonDetailPage.tsx
  src/pages/PeoplePage/PersonDetailPage/index.ts
  src/pages/PeoplePage/PersonListPage/PersonListPage.stories.tsx
  src/pages/PeoplePage/PersonListPage/PersonListPage.tsx
  src/pages/PeoplePage/PersonListPage/index.ts
  src/pages/PeoplePage/index.ts
  src/setupTests.ts
  src/theme/variables.css
Labels: effort: 2, priority: soon, type: feat

#7 feat: add contact button
  src/components/AddContactButton/AddContactButton.spec.tsx
  src/components/AddContactButton/AddContactButton.stories.tsx
  src/components/AddContactButton/AddContactButton.tsx
  src/components/AddContactButton/index.ts
Labels: effort: 1, priority:2day, type: feat

#9 feat: add person details page
  .storybook/preview.tsx
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/@types/fluro.d.ts
  src/components/PersonDetail/PersonDetail.spec.tsx
  src/components/PersonDetail/PersonDetail.stories.tsx
  src/components/PersonDetail/PersonDetail.tsx
  src/components/PersonDetail/index.ts
  src/components/Tabs/Tabs.tsx
  src/lib/queries/getContact/getContact.handlers.ts
  src/lib/queries/getContact/getContact.ts
  src/lib/queries/getContact/index.ts
  src/mocks/mswServer.ts
  src/pages/PeoplePage/PeoplePage.tsx
  src/pages/PeoplePage/PersonDetailPage/PersonDetailPage.stories.tsx
  src/pages/PeoplePage/PersonDetailPage/PersonDetailPage.tsx
  src/setupTests.ts
Labels: effort: 8, priority: now, type: feat

#8 feat: process definitions
  src/@types/fluro.d.ts
  src/lib/queries/getProcessDefinitions/getProcessDefinitions.handlers.ts
  src/lib/queries/getProcessDefinitions/getProcessDefinitions.ts
  src/lib/queries/getProcessDefinitions/index.ts
  src/pages/PeoplePage/PersonListPage/PersonListPage.tsx
Labels: effort: 2, priority: now, type: feat

#10 feat: timeline and processes
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/@types/fluro.d.ts
  src/components/PersonDetail/Info/Info.spec.tsx
  src/components/PersonDetail/Info/Info.stories.tsx
  src/components/PersonDetail/Info/Info.tsx
  src/components/PersonDetail/Info/index.ts
  src/components/PersonDetail/PersonDetail.spec.tsx
  src/components/PersonDetail/PersonDetail.stories.tsx
  src/components/PersonDetail/PersonDetail.tsx
  src/components/PersonDetail/Timeline/Default/Default.tsx
  src/components/PersonDetail/Timeline/Default/index.ts
  src/components/PersonDetail/Timeline/Post/Post.tsx
  src/components/PersonDetail/Timeline/Post/index.ts
  src/components/PersonDetail/Timeline/Timeline.spec.tsx
  src/components/PersonDetail/Timeline/Timeline.stories.tsx
  src/components/PersonDetail/Timeline/Timeline.tsx
  src/components/PersonDetail/Timeline/index.ts
  src/lib/queries/getContact/getContact.handlers.ts
  src/lib/queries/getContactTimeline/getContactTimeline.handlers.ts
  src/lib/queries/getContactTimeline/getContactTimeline.ts
  src/lib/queries/getContactTimeline/index.ts
  src/pages/PeoplePage/PersonDetailPage/PersonDetailPage.stories.tsx
  src/pages/PeoplePage/PersonDetailPage/PersonDetailPage.tsx
Labels: effort: 5, priority: now, type: feat

#12 feat: add process page
  .eslintignore
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/@types/fluro.d.ts
  src/components/App/App.tsx
  src/components/PersonDetail/Info/Info.spec.tsx
  src/components/PersonDetail/Info/Info.tsx
  src/components/ProcessDetail/ProcessDetail.spec.tsx
  src/components/ProcessDetail/ProcessDetail.stories.tsx
  src/components/ProcessDetail/ProcessDetail.tsx
  src/components/ProcessDetail/index.ts
  src/components/Router/Router.tsx
  src/components/TaskItem/Drawer/Drawer.spec.tsx
  src/components/TaskItem/Drawer/Drawer.stories.tsx
  src/components/TaskItem/Drawer/Drawer.tsx
  src/components/TaskItem/Drawer/index.ts
  src/components/TaskItem/TaskItem.spec.tsx
  src/components/TaskItem/TaskItem.stories.tsx
  src/components/TaskItem/TaskItem.tsx
  src/components/TaskItem/index.ts
  src/lib/mutations/updateProcess/updateProcess.handlers.ts
  src/lib/mutations/updateProcess/updateProcess.hook.ts
  src/lib/mutations/updateProcess/updateProcess.ts
  src/lib/queries/getContact/getContact.handlers.ts
  src/lib/queries/getContact/getContact.ts
  src/lib/queries/getContactTimeline/getContactTimeline.handlers.ts
  src/lib/queries/getProcess/getProcess.handlers.ts
  src/lib/queries/getProcess/getProcess.ts
  src/lib/queries/getProcess/index.ts
  src/lib/queries/getProcessDefinitions/getProcessDefinitions.handlers.ts
  src/lib/queries/getProcessDefinitions/getProcessDefinitions.ts
  src/pages/ProcessDetailPage/ProcessDetailPage.tsx
  src/pages/ProcessDetailPage/index.ts
  src/setupTests.ts
  src/tests/lib/helpers.tsx
Labels: effort: 8, priority: now, type: feat

#11 feat: add process list and list item
  src/@types/fluro.d.ts
  src/components/PersonList/PersonList.spec.tsx
  src/components/PersonList/PersonList.stories.tsx
  src/components/PersonList/PersonList.tsx
  src/components/PersonList/index.ts
  src/components/PersonListItem/PersonListItem.spec.tsx
  src/components/PersonListItem/PersonListItem.tsx
  src/components/PersonListItem/index.ts
  src/lib/queries/getContacts/getContacts.handlers.ts
  src/lib/queries/getContacts/getContacts.ts
  src/lib/queries/getContacts/index.ts
  src/lib/queries/getProcessDefinitions/getProcessDefinitions.handlers.ts
  src/lib/useAuth/useAuth.tsx
  src/pages/PeoplePage/PersonListPage/PersonListPage.stories.tsx
  src/pages/PeoplePage/PersonListPage/PersonListPage.tsx
Labels: effort: 3, priority:2day, type: feat

#13 fix: definitions and add post type
  src/components/PersonDetail/Info/Info.spec.tsx
  src/components/PersonDetail/Info/Info.tsx
  src/components/PersonDetail/PersonDetail.stories.tsx
  src/components/PersonList/PersonList.spec.tsx
  src/components/PersonList/PersonList.stories.tsx
  src/components/PersonList/PersonList.tsx
  src/components/PersonListItem/PersonListItem.spec.tsx
  src/components/PersonListItem/PersonListItem.tsx
  src/lib/queries/getDefinitions/getDefinitions.handlers.ts
  src/lib/queries/getDefinitions/getDefinitions.ts
  src/lib/queries/getDefinitions/index.ts
  src/lib/queries/getProcessDefinitions/getProcessDefinitions.ts
  src/lib/queries/getProcessDefinitions/index.ts
  src/pages/PeoplePage/PersonDetailPage/PersonDetailPage.stories.tsx
  src/pages/PeoplePage/PersonListPage/PersonListPage.stories.tsx
Labels: effort: 2, priority:2day, type: fix, type: refactor

#15 feat: add realm select
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/components/PersonDetail/PersonDetail.stories.tsx
  src/components/PersonDetail/Timeline/Timeline.stories.tsx
  src/components/RealmSelect/RealmSelect.spec.tsx
  src/components/RealmSelect/RealmSelect.stories.tsx
  src/components/RealmSelect/RealmSelect.tsx
  src/components/RealmSelect/Select/Select.spec.tsx
  src/components/RealmSelect/Select/Select.stories.tsx
  src/components/RealmSelect/Select/Select.tsx
  src/components/RealmSelect/Select/index.ts
  src/components/RealmSelect/TreeView/TreeView.spec.tsx
  src/components/RealmSelect/TreeView/TreeView.stories.tsx
  src/components/RealmSelect/TreeView/TreeView.tsx
  src/components/RealmSelect/TreeView/index.ts
  src/components/RealmSelect/index.ts
  src/components/TaskItem/TaskItem.stories.tsx
  src/lib/queries/getRealmSelectable/getRealmSelectable.handlers.ts
  src/lib/queries/getRealmSelectable/getRealmSelectable.ts
  src/lib/queries/getRealmSelectable/index.ts
  src/lib/useAuth/index.ts
  src/lib/useAuth/useAuth.tsx
Labels: effort: 5, priority: now, type: feat

#17 refactor: get definitions into a hook
  src/components/PersonDetail/Info/Info.tsx
  src/components/PersonList/PersonList.tsx
  src/components/PersonListItem/PersonListItem.spec.tsx
  src/components/PersonListItem/PersonListItem.tsx
  src/lib/queries/getDefinitions/getDefinitions.handlers.ts
  src/lib/queries/getDefinitions/getDefinitions.hook.ts
  src/lib/queries/getDefinitions/getDefinitions.ts
  src/lib/queries/getDefinitions/index.ts
Labels: effort: 3, priority: now, type: refactor

#16 refactor: move outlets into components
  src/components/App/App.tsx
  src/components/AppRouterOutlet/AppRouterOutlet.tsx
  src/components/AppRouterOutlet/index.ts
  src/components/PersonDetail/PersonDetail.tsx
  src/components/PersonListItem/PersonListItem.tsx
  src/components/PersonRouterOutlet/PersonRouterOutlet.stories.tsx
  src/components/PersonRouterOutlet/PersonRouterOutlet.tsx
  src/components/PersonRouterOutlet/index.ts
  src/components/Router/index.ts
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/index.ts
  src/pages/FaithSteps/FaithSteps.tsx
  src/pages/FaithSteps/index.ts
  src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/MinistryChain/MinistryChain.tsx
  src/pages/MinistryChain/index.ts
  src/pages/PeoplePage/PeoplePage.tsx
  src/pages/PeoplePage/index.ts
  src/pages/PersonDetailPage/PersonDetailPage.stories.tsx
  src/pages/PersonDetailPage/PersonDetailPage.tsx
  src/pages/PersonDetailPage/index.ts
  src/pages/PersonListPage/PersonListPage.stories.tsx
  src/pages/PersonListPage/PersonListPage.tsx
  src/pages/PersonListPage/index.ts
  src/pages/ProcessDetailPage/ProcessDetailPage.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Profile/index.ts
Labels: effort: 3, priority: now, type: refactor

#20 fix: add helper text and error to realm select
  src/components/RealmSelect/RealmSelect.spec.tsx
  src/components/RealmSelect/RealmSelect.tsx
  src/components/RealmSelect/Select/Select.spec.tsx
  src/components/RealmSelect/Select/Select.tsx
Labels: effort: 5, priority: now, type: fix

#19 chore: update react query
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/components/App/App.tsx
  src/components/PersonDetail/Info/Info.spec.tsx
  src/components/PersonDetail/Info/Info.tsx
  src/components/PersonDetail/PersonDetail.spec.tsx
  src/components/PersonDetail/PersonDetail.tsx
  src/components/PersonDetail/Timeline/Timeline.spec.tsx
  src/components/PersonDetail/Timeline/Timeline.tsx
  src/components/PersonList/PersonList.spec.tsx
  src/components/PersonList/PersonList.tsx
  src/components/ProcessDetail/ProcessDetail.tsx
  src/components/RealmSelect/RealmSelect.tsx
  src/lib/mutations/updateProcess/updateProcess.hook.ts
  src/lib/mutations/updateProcess/updateProcess.ts
  src/lib/queries/getDefinitions/getDefinitions.hook.ts
  src/tests/lib/helpers.tsx
Labels: effort: 1, priority: now, type: chore

#22 fix: nest process detail page under person detail page
  src/components/AppRouterOutlet/AppRouterOutlet.tsx
  src/components/PersonDetail/Info/Info.spec.tsx
  src/components/PersonDetail/Info/Info.tsx
  src/components/PersonRouterOutlet/PersonRouterOutlet.tsx
Labels: effort: 1, priority: now, type: fix

#18 feat: add contact
  package-lock.json
  package.json
  src/@types/fluro.d.ts
  src/components/AddContactButton/AddContactButton.spec.tsx
  src/components/AddContactButton/AddContactButton.stories.tsx
  src/components/AddContactButton/AddContactButton.tsx
  src/components/ContactForm/ContactForm.spec.tsx
  src/components/ContactForm/ContactForm.stories.tsx
  src/components/ContactForm/ContactForm.tsx
  src/components/ContactForm/index.ts
  src/components/PersonList/PersonList.spec.tsx
  src/components/PersonList/PersonList.tsx
  src/lib/mutations/createContact.handlers.ts
  src/lib/mutations/createContact.ts
Labels: effort: 8, priority: now, type: feat
