Repository slnz/go, pull requests merged in 2023-02, with the labels that each got.

#26 feat: text area component for postform
  src/components/PostForm/FieldRenderer/FieldRenderer.stories.tsx
  src/components/PostForm/FieldRenderer/FieldRenderer.tsx
  src/components/PostForm/components/TextArea/TextArea.spec.tsx
  src/components/PostForm/components/TextArea/TextArea.tsx
  src/components/PostForm/components/TextArea/index.ts
Labels: effort: 2, priority: soon, type: feat

#25 fix: contact creation redirect to add to process
  src/components/AddContactButton/AddContactButton.spec.tsx
  src/components/AddContactButton/AddContactButton.tsx
  src/components/AddProcessButton/AddProcessButton.tsx
  src/components/AddProcessButton/Dialog/Dialog.tsx
  src/pages/PersonDetailPage/PersonDetailPage.tsx
Labels: effort: 2, priority: now, type: fix

#27 feat: date select component
  package-lock.json
  package.json
  src/components/PostForm/FieldRenderer/FieldRenderer.stories.tsx
  src/components/PostForm/FieldRenderer/FieldRenderer.tsx
  src/components/PostForm/components/DateSelectField/DateSelectField.spec.tsx
  src/components/PostForm/components/DateSelectField/DateSelectField.tsx
  src/components/PostForm/components/DateSelectField/index.ts
Labels: effort: 3, priority: soon, type: feat
